### ISSUE TITLE
Hardcoded python shebang is not universal

### ISSUE THREAD

**Issue by triangulum** [blueset/alfred-search-unicode#1]
(Firstly, thanks for the great workflow!)

# Issue

The hard-coded shebang `#!/usr/local/bin/python3` is not universal for all python installations. This causes the workflow to fail.

![posix_spawn_error](https://user-images.githubusercontent.com/22440652/85189551-65075d80-b2f3-11ea-8b08-558dc1b50553.png)

# Notes

I realise that it is suggested to install python via homebrew, but that is extra work, requires extra storage, and could very easily cause conflicts with existing python installations. For example, I am using the Anaconda installation of python at `/Users/markus/opt/anaconda3/bin/python3`.

# Suggestions

Changing the shebang manually to `#!/Users/markus/opt/anaconda3/bin/python3` works.

However, it would make the most sense to use environment variable `#!/usr/bin/env python3`. As noted in some forum posts, Alfred doesn't seem to [support this](https://www.alfredforum.com/topic/1870-running-a-python-script-shebang-and-environment/) though, or only in [certain circumstances](https://www.alfredforum.com/topic/14685-alfred-uses-python-37-instead-of-382/).

It might be worth investigating a workaround. For example, a bash shell with access to `/usr/bin/env python3` could call the python scripts. Alternatively, the python3 executable path could be configured upon installation of the workflow.

**Comment by blueset** [comment]
Hi, thanks for the great detailed issue!

Do you think a bash script running `/usr/bin/env python3 script.py "{query}"` will work as a fix?

![image](https://user-images.githubusercontent.com/553831/86878127-db40f800-c11a-11ea-9fc9-c0d3ac1c05e0.png)

**Comment by templeman** [comment]
I ran into this issue as well. I tried the method mentioned above - setting as a bash script running `/usr/bin/env python3 unicode_identify.py "{query}"` - but got the same error as before.

In my case I have python versions managed via [pyenv](https://github.com/pyenv/pyenv), so manually changing the shebang to `#!/Users/templeman/.config/pyenv/versions/3.7.7/bin/python3` is what got it working for me.
