### ISSUE TITLE
uni app is unverified on first use

### ISSUE THREAD

**Issue by valrus** [blueset/alfred-search-unicode#3]
Attempting to use this workflow gives the following (macOS 11.5.2):
<img width="281" alt="Screen Shot 2021-10-07 at 11 04 58 AM" src="https://user-images.githubusercontent.com/343665/136439289-8ec1cb09-d443-4076-9658-4d021a9e30d1.png">

It can be resolved by:
* Alfred Preferences > Workflows section
* Right-click "Search Unicode" > "Open in Finder"
* Right-click the "uni" executable and choose "Open" and allow it to run, then quit Terminal or close the window

If the uni executable can't be verified can you please add this to the README?

**Comment by blueset** [comment]
Thanks for the report.

Unfortunately I’m not the author of [`uni`](https://github.com/arp242/uni) and I don’t have an Apple Developer subscription to sign the binary. 
I’ll add a section in the `README` file to address the issue.

**Comment by dennisosaj** [comment]
Please add it to the Installation Instructions.
