### ISSUE TITLE
Support emoji skin tone

### ISSUE THREAD

**Issue by acherunilam** [blueset/alfred-search-unicode#4]
Can we add support for specifying the skin tone through a [Workflow Environment Variable](https://www.alfredapp.com/help/workflows/advanced/variables/)?

Fwiw [uni](https://github.com/arp242/uni#emoji) natively supports skin tones, so it should be straightforward to implement.

**Comment by blueset** [comment]
Sounds like a great idea, I added gender and skin tone options to the workflow. Thanks for the suggestion!

<img width="439" alt="e_config" src="https://user-images.githubusercontent.com/553831/216904229-f7ee6f59-2d3a-4143-a654-c2b2fb0cb999.png">
